server:
  port: 8085

spring:
  application:
    name: valio-auth-service

  profiles:
    active: dev

  config:
    import:
      - configserver:http://configserver:8083
      - optional:classpath:env-dev.yaml