server:
  port: 8086

spring:
  application:
    name: valio_admin_service

  profiles:
    active: dev

  config:
    import: 
      - configserver:http://localhost:8084
      - optional:classpath:env.yaml