server:
  port: 8084

spring:
  application:
    name: valio_configserver

  profiles:
    active: git

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Puthvattana2026/VALIO_BACKEND.git
          clone-on-start: true
          default-label: main
          search-paths: configserver/src/main/resources/configs