server:
  port: 8087

spring:
  application:
    name: valio-guest-service

  profiles:
    active: dev 

  config:
    import:
    - configserver:http://configserver:8083
    - classpath:env-dev.yaml