server:
  port: 8088

spring:
  application:
    name: valio-housekeeper-service

  profiles:
    active: default 

  config:
    import:
    - configserver:http://localhost:8083
    - classpath:env.yaml
