server:
  port: 8089

spring:
  application:
    name: valio-receptionist-service

  profiles:
    active: dev 

  config:
    import:
    - configserver:http://localhost:8083
    - classpath:env-dev.yaml
