server:
  port: 8095

spring:
  application:
    name: valio-apigateway-service

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

  profiles:
    active: default

  config:
    import:
    - configserver:http://localhost:8083

